#GESTURES 0.51.0
gesture = 3, vertical, workspace
gesture = 3, left, dispatcher, layoutmsg, move +col
gesture = 3, right, dispatcher, layoutmsg, move -col
gesture = 4, vertical, fullscreen
#gesture = 3, down, float
