# YOU CAN ADD YOUR OWN CONFIGURATIONS IN userprefs.conf file, if you don't want to make a mess...
# Note: as userprefs.conf is sourced at the end, settings configured in this file will override the defaults

$scrPath = ${SCRIPTS_DIR_PATH} # set scripts path

# MONITORS -> Edit in monitors.conf
xwayland {
    force_zero_scaling = true
}

# LOCKSCREEN
exec-once = hyprlock

# GENERAL SETTINGS
general {
    gaps_out = 1
    gaps_in = 1
    border_size = 2
    col.active_border = rgb(F0B4DF)
    layout = scrolling
    resize_on_border = true
    extend_border_grab_area = 20
}

decoration {
    rounding = 10
    rounding_power = 4.0
    
    dim_inactive = true
    dim_strength = 0.2
    dim_special = 0.8
    
    active_opacity = 1.0
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0

    shadow {
	    enabled=false
    }

    blur {
	    enabled = yes
	    
        size = 4
	    passes = 3
	    noise = 0.02
	    contrast = 1.0
	    vibrancy = 1.0
	    brightness = 0.6
	    
        new_optimizations = on
        ignore_opacity = true
	    xray = false
	    special = false
	    
        popups = true
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }
}

# INPUT SETTINGS
input {
    kb_layout = us
    repeat_delay = 250
    repeat_rate = 35
    numlock_by_default = true
    
    follow_mouse = 1
    sensitivity = 0.3
    force_no_accel = 1

    focus_on_close = 1

    touchpad {
        natural_scroll = true
	    disable_while_typing = false
	    tap-to-click = true
    }
}

#DWINDLE
# dwindle {
#     pseudotile = true
#     preserve_split = true
# }

# SCROLLING
# scrolling {

# }

# DEBUG
debug {
	disable_logs = false
	disable_time = false
}

#MISC
misc {
    vfr = true
    vrr = 0

    animate_manual_resizes = false
    animate_mouse_windowdragging = false

    disable_splash_rendering = true
    disable_hyprland_logo = true
    force_default_wallpaper = 0

    on_focus_under_fullscreen = 2
    allow_session_lock_restore = true
    middle_click_paste = false
    focus_on_activate = true
    session_lock_xray = true

    mouse_move_enables_dpms = true
    key_press_enables_dpms = true

}

# SOURCES
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/execs.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/monitors.conf 
source = ~/.config/hypr/gestures.conf
source = ~/.config/hypr/misc.conf